name = "binjauction"
pages_build_output_dir = "dist"
compatibility_flags = []
compatibility_date = "2025-02-14"

[vars]
NODE_VERSION = "20.18.2"
VITE_BUCKET_BASE_URL = "https://binjauction-images.davidwhy.me"
VITE_BACKEND_BASE_URL = "/api"
VITE_FOOTER = "© 2025 david-why"

[[d1_databases]]
binding = "DB"
database_name = "binjauction2"
database_id = "bf35c228-3d94-4918-830c-710b7ef5beae"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "binjauction-images"
